### ISSUE TITLE
[RFC] 9.0 Roadmap

### ISSUE THREAD

**Issue by joelwurtz** [jolicode/automapper#97]
Here is a list of things that would be nice to be available for a first version of the 9.0 : 

 * [x] Api Platform integration (PR in draft #95 ) no need to be 100% complete, it will be expiremental and fixes / support for specific features will come with other 9.X versions
 * [x] Add a way to migrate from symfony serializer / api platform to automapper step by step (a.k.a specifying which object should use our normalizer, other will use existing normalizer) ref #98 
 * [x] Add a better DX to register mapper to build during cache warmup ref https://github.com/jolicode/automapper/pull/114
 * [x] Ensure some behavior of automapper is the same as the symfony / serializer by default when using the normalizer ref #101 
 * [x] Debug mode (command + profiler) inside symfony ref https://github.com/jolicode/automapper/pull/103
 * [x] Related to debug, think what would be best by default in dev env for loader (eval ? file ?) ref https://github.com/jolicode/automapper/pull/102
 * [x] Ensure cache related options are consistent and properly nammed
 
 List of things that could be nice, but could be added after the first release : 
 
 * [ ] Add a way to configure mapper other than using Attribute, like configuration file in PHP, xml or yaml
 * [ ] Add more configuration parameters for a specific mapper 
    * [x] Allow to disable / enable check attribute for a specific mapper and/or property  ref https://github.com/jolicode/automapper/pull/114 
    * [ ] Allow to set default date format for a specific mapper and/or property
    * [x] Allow to disable constructor for a specific mapper  ref https://github.com/jolicode/automapper/pull/114 
    * [ ] Allow to map private properties for a specific mapper
